-- Planned Jobs table
create table if not exists planned_jobs (
    id text primary key,
    order_id text references orders (id) on delete cascade,
    facility text not null,
    printing_status text not null,
    wo_status text not null,
    sla numeric not null,
    ageing integer not null,
    machine_name text not null,
    schedule_date timestamptz not null,
    ed_date timestamptz not null,
    retailer text not null,
    product_id text not null,
    base_paper text not null,
    current_wc text not null,
    production_type text not null,
    balance_qty integer not null,
    balance_value numeric not null,
    pi_number text not null,
    wo_quantity integer not null,
    no_of_plates integer not null,
    cs_name text not null,
    line_count integer not null,
    next_wc text not null,
    oos boolean not null default false,
    stage text not null,
    operator text not null,
    shift text not null,
    ai_suggestion text,
    created_at timestamptz not null default now()
);

-- Seed Planned Jobs
insert into
    planned_jobs (
        id,
        order_id,
        facility,
        printing_status,
        wo_status,
        sla,
        ageing,
        machine_name,
        schedule_date,
        ed_date,
        retailer,
        product_id,
        base_paper,
        current_wc,
        production_type,
        balance_qty,
        balance_value,
        pi_number,
        wo_quantity,
        no_of_plates,
        cs_name,
        line_count,
        next_wc,
        oos,
        stage,
        operator,
        shift
    )
values (
        'TL10002779',
        'ORD-1001',
        'Heat Transfer',
        'Pending',
        'High',
        2.5,
        6,
        'M1 - Heat Press',
        now(),
        now() + interval '2 days',
        'THE CHILDREN''S PLACE || US',
        'TCP-105871-WHT',
        'TCP-105871-WHT',
        'PLANNING [Awaiting Job]',
        'Sales Order',
        5000,
        15000,
        'PI10/25-26/26069',
        10000,
        2,
        'Sarah Jenkins',
        1,
        'Printing',
        false,
        'pre-press',
        'Mike R.',
        'morning'
    ),
    (
        'TL10002780',
        'ORD-1002',
        'Off Set',
        'Ongoing',
        'Medium',
        4.0,
        2,
        'SM-52 Heidelberg (2c)',
        now(),
        now() + interval '3 days',
        'ZARA || ES',
        'ZRA-9988-GLS',
        'ZRA-GLS-300G',
        'Printing',
        'Sales Order',
        2000,
        8500,
        'PI10/25-26/26070',
        8000,
        4,
        'David Chen',
        2,
        'Cutting',
        false,
        'press',
        'Sarah L.',
        'afternoon'
    ),
    (
        'TL10002781',
        'ORD-1003',
        'Digital',
        'Error',
        'High',
        1.0,
        7,
        'HP INDIGO 7900 (7C)',
        now() - interval '1 day',
        now() + interval '1 day',
        'H&M || SE',
        'HM-445-MAT',
        'HM-MAT-250G',
        'Printing',
        'Sales Order',
        4500,
        12000,
        'PI10/25-26/26071',
        5000,
        0,
        'Elena Rust',
        1,
        'Packaging',
        true,
        'press',
        'Tom K.',
        'night'
    ),
    (
        'TL10002782',
        'ORD-1004',
        'Off Set',
        'Completed',
        'Low',
        12.0,
        1,
        'SX-52 (4C+ COATING)',
        now() - interval '2 days',
        now() - interval '1 day',
        'UNIQLO || JP',
        'UNI-221-COT',
        'UNI-COT-150G',
        'Packaging',
        'Sales Order',
        0,
        0,
        'PI10/25-26/26072',
        10000,
        4,
        'Sarah Jenkins',
        3,
        'Dispatch',
        false,
        'post-press',
        'Alex W.',
        'morning'
    ),
    (
        'TL10002783',
        'ORD-1001',
        'Heat Transfer',
        'Ongoing',
        'Medium',
        6.5,
        3,
        'M2 - Roll Press',
        now(),
        now() + interval '4 days',
        'THE CHILDREN''S PLACE || US',
        'TCP-105872-BLK',
        'TCP-105872-BLK',
        'Printing',
        'Sample Order',
        1500,
        4500,
        'PI10/25-26/26073',
        3000,
        1,
        'Sarah Jenkins',
        1,
        'Cutting',
        false,
        'press',
        'Mike R.',
        'morning'
    ),
    (
        'TL10002784',
        'ORD-1002',
        'Digital',
        'Pending',
        'Low',
        24.0,
        0,
        'KM AccurioPress',
        now() + interval '1 day',
        now() + interval '5 days',
        'LEVIS || US',
        'LEV-501-TAG',
        'LEV-TAG-350G',
        'Pre-flight',
        'Sales Order',
        20000,
        45000,
        'PI10/25-26/26074',
        20000,
        0,
        'Elena Rust',
        1,
        'Printing',
        false,
        'pre-press',
        'Tom K.',
        'afternoon'
    ),
    (
        'TL10002785',
        'ORD-1003',
        'Off Set',
        'Ongoing',
        'High',
        1.5,
        5,
        'SM-52 Heidelberg (2c)',
        now(),
        now() + interval '1 day',
        'GAP || UK',
        'GAP-887-CRD',
        'GAP-CRD-400G',
        'Coating',
        'Sales Order',
        800,
        3200,
        'PI10/25-26/26075',
        5000,
        2,
        'David Chen',
        1,
        'Die-cut',
        false,
        'post-press',
        'Sarah L.',
        'afternoon'
    ),
    (
        'TL10002786',
        'ORD-1004',
        'Heat Transfer',
        'Error',
        'High',
        0.5,
        8,
        'M1 - Heat Press',
        now() - interval '2 days',
        now() + interval '1 day',
        'PRIMARK || IE',
        'PRI-112-LBL',
        'PRI-LBL-100G',
        'Printing',
        'Sales Order',
        10000,
        25000,
        'PI10/25-26/26076',
        15000,
        2,
        'Elena Rust',
        4,
        'Cutting',
        true,
        'press',
        'Mike R.',
        'night'
    ) on conflict (id) do nothing;